### ISSUE TITLE
一直显示离线状态

### ISSUE THREAD

**Issue by ggandycong** [wapznw/aria2desktop#1]
怎么设置呢？

**Comment by wapznw** [comment]
你使用的网页版吗？如果没有使用过aria2，推荐下载客服端体验。

**Comment by ggandycong** [comment]
我下载了客户端。windows。现在依然能处于离线状态。不知道还要怎么配置。

**Comment by wapznw** [comment]
windows一般是防火墙导致的

**Comment by ggandycong** [comment]
我在windows上关闭防火墙，杀毒软件等等。软件使用默认设置，但是还是处于离线状态。

**Comment by iOlduncle** [comment]
windows上关闭防火墙，无杀软，使用默认设置，一直是离线状态。

**Comment by qq7119** [comment]
一直是离线状态。同样的问题

**Comment by underlaw** [comment]
启动时，不会弹出防火墙设置，我也是下载了，打开aria2没有启动

**Comment by wapznw** [comment]
软件启动时无法联动aria2启动
