### ISSUE TITLE
软件非常漂亮，功能还可加强

### ISSUE THREAD

**Issue by underlaw** [wapznw/aria2desktop#4]
我系统是win10
地址复制是不能用右键剪切 粘贴那些的，但我在源码里看到好像有右键功能！
软件启动时无法联动aria2启动，但看源码里有个ariacli，作者的意图应该是可能联动启动的！

请问以上怎么解决了？

**Comment by wapznw** [comment]
内置aria2使用的默认端口为6800，如果该端口被占用了就无法启动内置的aria2

**Comment by underlaw** [comment]
还是不行，我任务管理器看了，没有aira2进程，打开aria2-desktop，还是无法启动aira2哦。

我用别的ui就可以，它也是自带aria2的！


这软件外观做的还是十分漂亮，如果加上  右键粘贴地址；右键能直接删除任务（包括本地删除）基本上完美了，至于设置自己弄config就行了

**Comment by wapznw** [comment]
windows已修复 软件启动时无法联动aria2启动 的问题
