### ISSUE TITLE
是否考虑内置aria2

### ISSUE THREAD

**Issue by luoei** [wapznw/aria2desktop#5]
内置或者在线自动安装的话，这样对用户体验比较好。

**Comment by wapznw** [comment]
已内置了 aria2，打包发布的安装包可以直接使用，不需要另外下载aria2的。

**Comment by luoei** [comment]
好的 辛苦了哈

**Comment by whisperice** [comment]
> 
> 
> 已内置了 aria2，打包发布的安装包可以直接使用，不需要另外下载aria2的。

请问下内置的aira2文件是哪个呢？可否手动替换更新aira？

**Comment by wapznw** [comment]
> > 已内置了 aria2，打包发布的安装包可以直接使用，不需要另外下载aria2的。
> 
> 请问下内置的aira2文件是哪个呢？可否手动替换更新aira？

用户home目录下的aria2-desktop文件夹中
windows应该在 c:\users\用户目录\aria2-desktop

**Comment by yuki-xin** [comment]
请问Mac版本有内置吗

**Comment by wapznw** [comment]
> 请问Mac版本有内置吗

有内置的
